---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runescrape-agent
  labels:
    app: runescrape-agent
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.runescrape-agent: glob:staging-continuous-*
  namespace: runescrape-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runescrape-agent
  template:
    metadata:
      labels:
        app: runescrape-agent
    spec:
      containers:
      - name: runescrape-agent
        image: iexalt/runescrape-agent:staging-continuous-20
        env:
        - name: RUNESCRAPE_SERVICE
          value: "runescrape-api.runescrape-staging"
        - name: RUNESCRAPE_ENDPOINT
          value: "items/history"
