kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: snapshot-pvc
  namespace: runescrape
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 830Gi
  dataSource:
    name: pvc-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
