apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: timescale-pass
  namespace: runescrape
spec:
  encryptedData:
    pass: AQAGepp49JwvkIUjuQYZPf8WLC/3zvkRwviO2tYHU+RiQmg2yoZ8OavxyKmOKZVVJtXaMb5fSJAPpz4Az4//7n5fmpqC/aipO6AqdijcigC9eU7wYTEkWPqmlcCstV/DkFIOHsg44Y595PGML6cYn/EAYJMBoZuwSjE0aPdOJYMr8eYLwt8SwtAdFiaVk3hkzC0BY15JPFIguXmLe9NYpHia+Y/6vWzqrTJRzw92XYFMQj/Deq/WhuK+q1Wp9mWAWe7ZTTFwSw7y6ezUEiQATyiapYgLZKmcm2jTD0px+pwlu5GVYbkd4JJ3VBkrTnqK4Xy0WymLmOJ8SrOvENdOIaXs/usnm0cpMx1L53VDJvVoB/Cbh81ON82zyA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: mysecret
      namespace: runescrape
status: {}
