kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: timescale-pvc
  labels:
    app: timescale
  namespace: runescrape
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 830Gi
