apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: runescrape-$NAMESPACE-$SUFFIX
  namespace: runescrape-$NAMESPACE
  labels:
    suffix: $SUFFIX
spec:
  hostname: runescrape.$NAMESPACE.$SUFFIX.analogsea.ca
  acmeProvider:
    email: cklliaw@uwaterloo.ca
  requestPolicy:
    insecure:
      action: Redirect
      additionalPort: 8080
