---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runescrape-agent
  labels:
    app: runescrape-agent
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.runescrape-agent: glob:master-continuous-*
  namespace: runescrape
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runescrape-agent
  template:
    metadata:
      labels:
        app: runescrape-agent
    spec:
      containers:
      - name: runescrape-agent
        image: iexalt/runescrape-agent:master-continuous-11
        env:
        - name: RUNESCRAPE_SERVICE
          value: "runescape-api.runescrape"
