---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
  namespace: runescrape-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      # - name: postgres
      #   image: postgres:11.7
      - name: timescale
        image: timescale/timescaledb:1.6.1-pg11
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: timescale-pass
              key: pass
        - name: PGDATA
          value: /postgresql/data
        volumeMounts:
        - mountPath: /postgresql
          name: postgres
      volumes:
      - name: postgres
        persistentVolumeClaim:
          claimName: postgres-pvc
