kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: timescale-clone-pvc
  namespace: runescrape-staging
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  dataSource:
    name: timescale-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
