apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: timescale-snapshot
  namespace: runescrape-staging
spec:
  snapshotClassName: rook-ceph-block-snapclass
  source:
    name: postgres-pvc
    kind: PersistentVolumeClaim
