---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-testing-2
  labels:
    app: pvc-testing-2
  namespace: runescrape-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pvc-testing-2
  template:
    metadata:
      labels:
        app: pvc-testing-2
    spec:
      containers:
      - name: timescale
        image: timescale/timescaledb:1.6.1-pg11
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: timescale-pass
              key: pass
        - name: PGDATA
          value: /postgresql/data
        volumeMounts:
        - mountPath: /postgresql
          name: timescale-clone-pvc
      volumes:
      - name: timescale-clone-pvc
        persistentVolumeClaim:
          claimName: postgres-pvc
