apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: postgres-pass
  namespace: flask-playground
spec:
  encryptedData:
    pass: AQCTFRK4MPgCNXQMb0vTlTw4Qqk4Fn8wiRxgB/vjS3JBhSe3DryifkX3FNibi3a/xbE3/M+si1YHkWFOArG1SU93dhD/JBKKgeGhqDm2Xai3p5kR3HMb5hZJGVdVaqklu26fCJNus+6fMRb7fVpVy7CInXeuzmodT54DuvQPVObRXLAJYI7tgBRFWb/gGu0iVDrLH2cDEwaGJArSdHAwD/VM4VSKR93NCoVnqJid9MlKh7xUZ/RBY+huMuPcB9W/+0SKvZzLp9DVeyIn5RKpW4CUfoFYvN2ggl++rKAznNklWzr7uYB65P9XSNswCFagcFEqb1nqCEEABLnUnhirdlrBQSl4YUNJkhWtLETlKpsWyCFJMqCA9YJUNA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: postgres-pass
      namespace: flask-playground
status: {}

