apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: agent-external
  namespace: agent
spec:
  prefix: /
  host: agent.analogsea.ca
  host_regex: true
  service: agent.agent:80
  ambassador_id: ambassador-http
