apiVersion: v1
kind: Service
metadata:
  name: timescale-bob
  namespace: runescrape-dev
  labels:
    suffix: bob
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: timescale-bob
    suffix: bob
