kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: timescale-pvc-bob
  labels:
    app: timescale
    suffix: bob
  namespace: runescrape-dev
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
