---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runescrape-agent-bob
  labels:
    app: runescrape-agent-bob
    suffix: bob
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.runescrape-agent: glob:dev-bob-continuous-*
  namespace: runescrape-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runescrape-agent-bob
      suffix: bob
  template:
    metadata:
      labels:
        app: runescrape-agent-bob
        suffix: bob
    spec:
      containers:
      - name: runescrape-agent
        image: iexalt/runescrape-agent:dev-bob-continuous-22
        env:
        - name: RUNESCRAPE_SERVICE
          value: "runescrape-api-bob.runescrape-dev"
        - name: RUNESCRAPE_ENDPOINT
          value: "items/history"
