apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  labels:
    app: agent
  namespace: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
      - name: agent
        image: iexalt/analogsea-kubernetes-agent:master-continuous-3
        ports:
        - containerPort: 8080
