---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  labels:
    app: agent
  namespace: agent
  annotations:
    fluxcd.io/automated: 'true'
    fluxcd.io/tag.agent: glob:iexalt/analogsea-kubernetes-agent:master-continuous-*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
      - name: agent
        image: iexalt/analogsea-kubernetes-agent:20190926T193337Z
        ports:
        - containerPort: 8080
