kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: snapshot-pvc
  labels:
    app: timescale-testing
  namespace: runescrape-staging
spec:
  storageClassName: rook-ext4
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  dataSource:
    name: original-pvc-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
