apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: runescrape-staging
  namespace: runescrape-staging
spec:
  hostname: runescrape.staging.analogsea.ca
  acmeProvider:
    email: cklliaw@uwaterloo.ca
