apiVersion: v1
kind: Service
metadata:
  name: runescrape-static
  namespace: runescrape-staging
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: runescrape-static
