apiVersion: v1
kind: Service
metadata:
  name: bobcraft-mc
  namespace: bobcraft
spec:
  type: NodePort
  ports:
  - port: 25565
    targetPort: 25565
    nodePort: 32556
  selector:
    app: bobcraft
---
apiVersion: v1
kind: Service
metadata:
  name: bobcraft-ssh
  namespace: bobcraft
spec:
  type: NodePort
  ports:
  - port: 22
    targetPort: 22
    nodePort: 30022
  selector:
    app: bobcraft
