kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bobcraft-pvc
  labels:
    app: bobcraft
  namespace: bobcraft
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
