kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: original-pvc
  namespace: runescrape-staging
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
