apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: pvc-snapshot
  namespace: runescrape-staging
spec:
  snapshotClassName: rook-ceph-block-snapclass
  source:
    name: original-pvc
    kind: PersistentVolumeClaim
