---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-testing
  labels:
    app: pvc-testing
  namespace: runescrape-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pvc-testing
  template:
    metadata:
      labels:
        app: pvc-testing
    spec:
      containers:
      - name: pvc-testing
        image: ubuntu:18.04
        volumeMounts:
        - mountPath: /mnt/pvc
          name: pvc
        command:
        - bash
        args: ["-c", "coproc { exec >&-; read; }; eval exec \"${COPROC[0]}<&-\"; wait"]
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: original-pvc
