apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescale
  labels:
    app: timescale
  namespace: runescrape
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescale
  template:
    metadata:
      labels:
        app: timescale
    spec:
      containers:
      - name: timescale
        image: timescale/timescaledb:1.4.2-pg11
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: timescale-pass
                key: pass
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: timescaledb
      volumes:
        - name: timescaledb
          persistentVolumeClaim:
            claimName: timescale-pvc
