apiVersion: v1
kind: Service
metadata:
  name: runescrape-static-bob
  namespace: runescrape-dev
  labels:
    suffix: bob
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: runescrape-static-bob
    suffix: bob
