---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runescrape-agent-$SUFFIX
  labels:
    app: runescrape-agent-$SUFFIX
    suffix: $SUFFIX
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.runescrape-agent: glob:$NAMESPACE-$SUFFIX-continuous-*
  namespace: runescrape-$NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runescrape-agent-$SUFFIX
      suffix: $SUFFIX
  template:
    metadata:
      labels:
        app: runescrape-agent-$SUFFIX
        suffix: $SUFFIX
    spec:
      containers:
      - name: runescrape-agent
        image: iexalt/runescrape-agent:$NAMESPACE-$SUFFIX
        env:
        - name: RUNESCRAPE_SERVICE
          value: "runescrape-api-$SUFFIX.runescrape-$NAMESPACE"
        - name: RUNESCRAPE_ENDPOINT
          value: "items/history"
