apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: runescrape-static
  namespace: runescrape-staging
spec:
  prefix: ".*view.*"
  prefix_regex: true
  rewrite: ""
  host: runescrape.staging.analogsea.ca
  service: runescrape-static.runescrape-staging:80
  cors:
    origins: "*"
  timeout_ms: 30000
