apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: runescrape-external-redirect
  namespace: runescrape
spec:
  prefix: /items/history
  host: runescrape.analogsea.ca
  method: POST
  host_redirect: true
  service: https://httpbin.org/post
  timeout_ms: 30000
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: runescrape-external
  namespace: runescrape
spec:
  prefix: /
  host: runescrape.analogsea.ca
  service: runescrape-api.runescrape:80
  cors:
    origins: "*"
  timeout_ms: 30000
