apiVersion: v1
kind: Service
metadata:
  name: runescrape-static-$SUFFIX
  namespace: runescrape-$NAMESPACE
  labels:
    suffix: $SUFFIX
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: runescrape-static-$SUFFIX
    suffix: $SUFFIX
